### PR TITLE
Refactored build process and publish to npm process

### PR DESCRIPTION
**Pull request by arthurvi**
Now when you do:
```
npm install --save react-time-input
```
Users get errors because the package is not built. We should add a `prepublish` step to `package.json` that is ran before npm publish. This builds the actual necessary file and publishes it to npm. Also react shouldn't be a dependency but a peer dependency. Otherwise this component was almost 1mb in size.

### CODE REVIEW

**Comment by arthurvi** [comment]
@dima-bu nice! Should we push the new version to npm?
Then we can just do 
```
npm install --save react-time-input
```
```
import TimeInput from 'react-time-input'
```

**Comment by dima-bu** [comment]
Of couse, thank you Arthur

**Comment by arthurvi** [comment]
@dima-bu Thanks, saw the update! Only thing is that the file published to npm still contains react as dependency. Probably because it was still in your node_modules folder. Is it possible to remove node_modules, do an npm install and then publish? That should prevent the inclusion of react.

**Comment by dima-bu** [comment]
Thank you, i added you in Collaborators. Can you talk your npm account? i want to add in npm too

**Comment by arthurvi** [comment]
Thanks! https://www.npmjs.com/~arthurvi is my npm account

**Pull request merged**
